#!/bin/sh

# 現在の git リポジトリの .git/hooks/ 以下へ
# フックを走らせるスクリプトへのsymlinkを貼っていく。既にフックがあるなら何もしない。

RUN_HOOK_DIR=$(dirname $(readlink -f $0))
COMMON_HOOK_PATH="${RUN_HOOK_DIR}/run-hooks"
HOOK_DIRS=$(ls -F ${RUN_HOOK_DIR} | grep '/' | cut -d'/' -f1)

GIT_HOOK_DIR=$(git rev-parse --git-dir)'/hooks'

for hook_name in ${HOOK_DIRS[@]}; do
    hook_path="${GIT_HOOK_DIR}/${hook_name}"
    if [ -e $hook_path ]; then
        if [ $(readlink -f $hook_path) = $COMMON_HOOK_PATH ]; then
            echo "SKIP ${hook_path} is already symlinked"
        else
            echo "SKIP ${hook_path} exists"
        fi
    elif [ -h $hook_path ]; then
        # -e では偽だけど -h では真になる => リンク切れの symlink,
        # hook ディレクトリ移動させたりした際にありそうなので教えてあげる。
        echo "SKIP maybe ${hook_path} is a dangling symlink"
    else
        echo "ln -s ${COMMON_HOOK_PATH} ${GIT_HOOK_DIR}/${hook_name}"
        ln -s "${COMMON_HOOK_PATH}" "${GIT_HOOK_DIR}/${hook_name}"
    fi
done
